### ISSUE TITLE
tko -  typescript import statement using webpack

### ISSUE THREAD

**Issue by joemcurry** [knockout/tko#57] opened 2018-01-23 17:58 UTC
So I've tried 
import * as ko from 'tko'
import 'tko'

can't seem to get ref to tko,  any help on that would be awesome

**Comment by brianmhunt** [comment] 2018-01-23 19:54
I'd need a bit more info about your setup to diagnose/prescribe -- how are you getting tko?

**Comment by joemcurry** [comment] 2018-01-23 23:30
Npm install tko

**Comment by joemcurry** [comment] 2018-01-23 23:39
Here a little more.. simple setup, visual studio code, webpack, npm install tko. Typescript ..

One index.ts file, trying to use tko.

**Comment by brianmhunt** [comment] 2018-01-24 13:41
I'm unable to reproduce with

### x.js
```javascript
import * as tko from 'tko'
console.log(tko)
```

Then in a shell

```bash
$ npm i tko
$ webpack --entry=./x.js y.js
```

Running `node y.js` works as expected.

Closing since this appears to be a support issue — it might be better to try stackoverflow, but if you find something about TKO that can be improved, please comment and we can re-open.

**Closed by brianmhunt** 2018-01-24 13:41 UTC

**Comment by wilson0x4d** [comment] 2024-06-24 18:16
FWIW -- the above "working example" is not typescript, it is javascript, and is not passing through `ts-loader` (which is why it would appear to work.)

Since this is a top result on google when investigating problems importing tko in typescript (aka `ts-loader`) via webpack, I hope this information is useful to others.

Consider the following "./index.ts" entry file that "should" work, but does not:

```typescript
import * as tko from '@tko/build.knockout'
console.log(tko)
```

If you are using [the "Recommended" tsconfig base](https://github.com/tsconfig/bases/blob/main/bases/recommended.json) you will receive the following error:

```markdown
ERROR in /home/user/code/tko_testing/src/index.ts
./index.ts 1:21-42
[tsl] ERROR in /home/user/code/tko_testing/src/index.ts(1,22)
      TS2307: Cannot find module '@tko/build.knockout' or its corresponding type declarations.
```

To work around this you can add a `compilerOptions.paths` entry for the module to your `tsconfig.json` -- be aware I am targeting evergreen browsers and thus have specified `browser.js` here, for other use you may require another file in the same directory, i wouldn't know and couldn't advise:

```json
{
    "compilerOptions": {
        // ... other options ...
        "paths": {
            "@tko/build.knockout": [ "./node_modules/@tko/build.knockout/dist/browser.js" ] // <-- this
        }
    }
}
```

Running webpack again results in yet another error:

```markdown
ERROR in /home/user/code/tko_testing/src/index.ts
./index.ts 1:21-42
[tsl] ERROR in /home/user/code/tko_testing/src/index.ts(1,22)
      TS7016: Could not find a declaration file for module '@tko/build.knockout'. '/home/user/code/tko_testing/node_modules/@tko/build.knockout/dist/browser.js' implicitly has an 'any' type.
```

This is because there are no typescript bindings available for @tko modules (neither `build.knockout` nor `build.reference`).  To work around this, albeit sadly, you can override the preferred/recommended compiler config `"noImplicitAny": false`.

```json
{
    "compilerOptions": {
       // ... other options ...
       "noImplicitAny": false,
    }
}
```

#### Success?

If you attempt to webpack again you should see a successful build result (or, at least, you should not see any errors.)  Your `tsconfig.json` would probably look something like this when you're done:

```json
{
    "compilerOptions": {
        // these options come from "Recommended" tsconfig base
        "target": "es2016",
        "module": "commonjs",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        // these options we added
        "noImplicitAny": false,
        "paths": {
            "@tko/build.knockout": [ "./node_modules/@tko/build.knockout/dist/browser.js" ]
        }
    }
}
```

#### webpack5 (the future)

As a final note, if you are using webpack5 and your project uses `es` (browser) modules instead of `commonjs` (transpiler) modules and imports (because that is the current state over all major browsers), there is a breaking change in the way es modules are resolved by webpack which affects tko (it's a tko defect, not a webpack defect, and this will become reported more and more over time) and so you'll need to apply an override rule for js/mjs files. What I mean is if your tsconfig contains this:

```json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext", // <-- this
```

Then your `webpack.config.js` will need a "rule" like this:

```json
{
    // ... other settings ...
    module: {
        rules: [
            // works around a breaking change in webpack5 that affects tko
            {
                test: /\.m?js$/,
                resolve: {
                    fullySpecified: false, // <-- this
                },
            },
```

#### takeways?

Obviously not ideal, some of the hard-to-swallow points that will turn the vast majority of potential consumers away:

* `@tko` does not resolve correctly and requires a path entry, while minor, users are left to figuring this out on their own.

* `@tko` seems to use non-qualified ES imports in ES (javascript) files which requires some tweaks in webpack5, while minor, users are left to figuring this out on their own.

* there are no definitely typed (*.d.ts) typings for `@tko`, this forces users to disable "noImplicitAny" which is normally a best-practice adopted in corporate/commercial/production TS development projects and thus this is a huge turn-off for adoption.

I have been using knockoutjs for well over a decade and this is the result of my first serious foray into adopting tko (ie. knockout4 instead of knockout3) for a new project.  I want this project to succeed, I'm not grinding anyone's gears here, but hopefully we get a non-alpha/non-beta release "soon" and also typescript typings for tko along with it. Virtually the entire industry has conformed around the use of TypeScript and webpack in the time since the knockout4 effort began and the limbo knockout has been in has slowly forced my hand from one employer to the next such that nobody is willing to invest money in using knockout anymore, instead Vue, Angular, and React have come to dominate the workplace despite being "vendor entrenching, over-engineered" bloatware.

**Comment by wilson0x4d** [comment] 2024-06-26 17:45
After some digging I was able to eliminate the need for `"noImplicitAny": false` option:

1. By either temporarily installing [the `@types/knockout` package](https://www.npmjs.com/package/@types/knockout) or pulling [the relevant `index.d.ts` directly](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knockout/index.d.ts) from the git repo.
2. Making a copy of the `index.d.ts` for knockout from the above package into a folder under `./src/` such as `./src/types/`, and giving it a unique and relevant name such as `./src/types/build.knockout.d.ts`
3. Modifying the copy made in step 2 so `declare module "knockout"` instead reads `declare module "@tko/build.knockout".
4. Updating our `tsconfig.json` so the paths alias for `@tko/build.knockout` references this new `.d.ts` file:

> NOTE: the paths seen here may need to be tweaked to match your specific use of webpack, but this should work as-is for most users:

```json
{
    "compilerOptions": {
        "paths": {
            "@tko/build.knockout": [
                "./node_modules/@tko/build.knockout/dist/browser.js",
                "./src/types/build.knockout.d.ts"
            ]
        }
    }
 }
```

This `index.ts` should compile, and when referenced from an html file via <script> tag should emit non-undefined values via the `console.log`:

```typescript
import ko from '@tko/build.knockout'

class MyViewModel {
    test : KnockoutObservable<string>;
    constructor() {
        this.test = ko.observable<string>("Hello, World!");
    }
};

const vm = new MyViewModel();

console.log([ko, ko.observable, ko.applyBindings]);

ko.applyBindings(vm);
```

HTML similar to the following can be used to confirm the viewmodel is binding as expected:

```html
<html>
    <head>
        <title>TKO TEST</title>
    </head>
    <body>
        <p><span data-bind="text: test">...</span></p>        
    </body>
    <script src="bundle.js"></script>
</html>
```

For completeness, here are the `tsconfig.json` and `webpack.config.js` we are using, you may not require all of the same settings, this is only provided for parity/verification from your end if you are having trouble replicating success:

```json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "skipLibCheck": true,
        "noImplicitAny": true,
        "lib": [
            "DOM",
            "ESNext"
        ],
        "paths": {
            "@tko/build.knockout": [
                "./node_modules/@tko/build.knockout/dist/browser.js",
                "./src/types/build.knockout.d.ts"
            ]
        }
    }
}
```

```js
const path = require('path')

module.exports = {
    context: path.resolve(__dirname, 'src'),
    entry: [
        './index.ts',
    ],
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
    },
    resolve: {
        extensions: [
            '.ts',
            '.js'
        ],
        modules: [
            path.join(__dirname, 'node_modules')
        ]
    },
    module: {
        rules: [
            {
                test: /\.(j|t)sx?$/,
                resolve: {
                    fullySpecified: false
                }
            },
            {
                test: /\.(j|t)sx?$/,
                exclude: /node_modules/,
                use: ['ts-loader'],
                resolve: {
                    fullySpecified: false
                }
            }
        ]
    }
}
```

Lastly, `package.json` dependency versions that we have tested with:

```json
{
  "devDependencies": {
    "ts-loader": "^9.5.1",
    "typescript": "^5.5.2",
    "webpack": "^5.92.1",
    "webpack-cli": "^5.1.4"
  },
  "dependencies": {
    "@tko/build.knockout": "^4.0.0-beta1.5"
  }
}
```

Hope this helps others.

As an aside, the `@types/knockout` definitions have not been verified to match, but limited testing of fundamental features show that it is sufficiently correct for our initial tests. Where differences from knockout3->knockout4 are obvious you will find the d.ts does not match (for example, there is no `ko.proxy` defined.)

Again, it would be preferred/ideal to see tko project include its own `index.d.ts` within the dist of `build.knockout` and `build.reference` -- developers such as myself can always alias it in as necessary and this would help eliminate an obvious hurdle in TypeScript adoption. Since the iteration cadence on TKO/knockout4 seems to be measured in "years" at this point, perhaps it's a good time to review `.d.ts` generation options -- for example [they can be built from JSDoc](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) and may not require as much manual labor as it would have in previous years.  Including typings would eliminate the third-party dependency on Microsoft for maintenance, especially if they can be generated at build-time from JSDoc comments. @brianmhunt @danieldickison  @SteveSanderson @mbest -- i am not involved enough in project maintenance to drive this effort or know if it is already tracked in a milestone somewhere.

Thanks!
